server:
  port: 8080

# DB
spring:
  datasource:
    url: # jdbc:postgresql://<AWS_RDS_ENDPOINT>:5432/postgres
    username: # aws username
    password: # aws password
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

# Swagger
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    doc-expansion: none
  paths-to-match:
    - /**  #애플리 케이션의 모든 api(엔드포인트)

jwt:
  header: AUTHORIZATION
  secret: HAEDALRentalListVe2132312rySecretKeyITisVERYIM00RTANT125112312HAEDALRentalListVe2132312rySecretKeyITisVERYIM00RTANT125112312HAEDALRentalListVe2132312rySecretKeyITisVERYIM00RTANT125112312


#logging:
#  level:
#    root: DEBUG # 모든 로거의 기본 레벨을 DEBUG로 설정
#    org.springframework.security: DEBUG # Spring Security 관련 로깅을 DEBUG로 설정
#    com.rental.haedal.auth: TRACE # 특정 패키지 로깅 레벨을 TRACE로 설정